export const INIT_ANALYSIS = "INIT_ANALYSIS";
export const INIT_ANALYSIS_SUCCESS = "INIT_ANALYSIS_SUCCESS";
export const INIT_ANALYSIS_FAILURE = "INIT_ANALYSIS_FAILURE";
export const INIT_ANALYSIS_RESET = "INIT_ANALYSIS_RESET";

export const GET_RUN_STATUS = "GET_RUN_STATUS";
export const GET_RUN_STATUS_SUCCESS = "GET_RUN_STATUS_SUCCESS";
export const GET_RUN_STATUS_FAILURE = "GET_RUN_STATUS_FAILURE";
export const GET_RUN_STATUS_RESET = "GET_RUN_STATUS_RESET";

export const SET_SELECTED_ATTRIBUTE_TAXONSET =
  "SET_SELECTED_ATTRIBUTE_TAXONSET";

export const STORE_CONFIG = "STORE_CONFIG";
export const STORE_CONFIG_RESET = "STORE_CONFIG_RESET";
export const RENAME_CONFIG = "RENAME_CONFIG";
export const DELETE_CONFIG = "DELETE_CONFIG";

export const GET_VALID_PROTEOME_IDS = "GET_VALID_PROTEOME_IDS";
export const GET_VALID_PROTEOME_IDS_SUCCESS = "GET_VALID_PROTEOME_IDS_SUCCESS";
export const GET_VALID_PROTEOME_IDS_FAILURE = "GET_VALID_PROTEOME_IDS_FAILURE";
export const GET_VALID_PROTEOME_IDS_RESET = "GET_VALID_PROTEOME_IDS_RESET";

export const SET_POLLING_LOADING = "SET_POLLING_LOADING";

export const GET_BATCH_STATUS = "GET_BATCH_STATUS";
export const GET_BATCH_STATUS_SUCCESS = "GET_BATCH_STATUS_SUCCESS";
export const GET_BATCH_STATUS_FAILURE = "GET_BATCH_STATUS_FAILURE";
export const GET_BATCH_STATUS_RESET = "GET_BATCH_STATUS_RESET";

export const UPDATE_SESSION_META = "UPDATE_SESSION_META";

export const GET_CLUSTERING_SETS = "GET_CLUSTERING_SETS";
export const GET_CLUSTERING_SETS_SUCCESS = "GET_CLUSTERING_SETS_SUCCESS";
export const GET_CLUSTERING_SETS_FAILURE = "GET_CLUSTERING_SETS_FAILURE";
export const GET_CLUSTERING_SETS_RESET = "GET_CLUSTERING_SETS_RESET";

export const SET_SELECTED_CLUSTER_SET = "SET_SELECTED_CLUSTER_SET";

export const GET_COLUMN_DESCRIPTIONS = "GET_COLUMN_DESCRIPTIONS";
export const GET_COLUMN_DESCRIPTIONS_SUCCESS =
  "GET_COLUMN_DESCRIPTIONS_SUCCESS";
export const GET_COLUMN_DESCRIPTIONS_FAILURE =
  "GET_COLUMN_DESCRIPTIONS_FAILURE";
export const GET_COLUMN_DESCRIPTIONS_RESET = "GET_COLUMN_DESCRIPTIONS_RESET";
