services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: kinfin-api
    volumes:
      - ./data:/app/data
      - /home/dinesh/tmp/kinfin:/kinfin # FIXED path
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: kinfin-ui
    ports:
      - "5173:80"
    depends_on:
      - api
